# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='admin.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61\x64min.proto\">\n\tCommReply\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.OperationStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyRequest\" \n\x0c\x41gentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\r\"0\n\x0eGenericMessage\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t**\n\x0fOperationStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\x9e\x01\n\x05\x61\x64min\x12+\n\x0c\x61gent_online\x12\r.AgentRequest\x1a\n.CommReply\"\x00\x12,\n\ragent_offline\x12\r.AgentRequest\x1a\n.CommReply\"\x00\x12:\n\x19\x61gent_general_use_message\x12\x0f.GenericMessage\x1a\n.CommReply\"\x00\x62\x06proto3')
)

_OPERATIONSTATUS = _descriptor.EnumDescriptor(
  name='OperationStatus',
  full_name='OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=179,
  serialized_end=221,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONSTATUS)

OperationStatus = enum_type_wrapper.EnumTypeWrapper(_OPERATIONSTATUS)
SUCCESS = 0
FAILED = 1



_COMMREPLY = _descriptor.Descriptor(
  name='CommReply',
  full_name='CommReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='CommReply.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='CommReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=77,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=93,
)


_AGENTREQUEST = _descriptor.Descriptor(
  name='AgentRequest',
  full_name='AgentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='AgentRequest.agent_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=127,
)


_GENERICMESSAGE = _descriptor.Descriptor(
  name='GenericMessage',
  full_name='GenericMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='GenericMessage.agent_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='GenericMessage.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=177,
)

_COMMREPLY.fields_by_name['status'].enum_type = _OPERATIONSTATUS
DESCRIPTOR.message_types_by_name['CommReply'] = _COMMREPLY
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['AgentRequest'] = _AGENTREQUEST
DESCRIPTOR.message_types_by_name['GenericMessage'] = _GENERICMESSAGE
DESCRIPTOR.enum_types_by_name['OperationStatus'] = _OPERATIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommReply = _reflection.GeneratedProtocolMessageType('CommReply', (_message.Message,), dict(
  DESCRIPTOR = _COMMREPLY,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:CommReply)
  ))
_sym_db.RegisterMessage(CommReply)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

AgentRequest = _reflection.GeneratedProtocolMessageType('AgentRequest', (_message.Message,), dict(
  DESCRIPTOR = _AGENTREQUEST,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:AgentRequest)
  ))
_sym_db.RegisterMessage(AgentRequest)

GenericMessage = _reflection.GeneratedProtocolMessageType('GenericMessage', (_message.Message,), dict(
  DESCRIPTOR = _GENERICMESSAGE,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:GenericMessage)
  ))
_sym_db.RegisterMessage(GenericMessage)



_ADMIN = _descriptor.ServiceDescriptor(
  name='admin',
  full_name='admin',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=224,
  serialized_end=382,
  methods=[
  _descriptor.MethodDescriptor(
    name='agent_online',
    full_name='admin.agent_online',
    index=0,
    containing_service=None,
    input_type=_AGENTREQUEST,
    output_type=_COMMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='agent_offline',
    full_name='admin.agent_offline',
    index=1,
    containing_service=None,
    input_type=_AGENTREQUEST,
    output_type=_COMMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='agent_general_use_message',
    full_name='admin.agent_general_use_message',
    index=2,
    containing_service=None,
    input_type=_GENERICMESSAGE,
    output_type=_COMMREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADMIN)

DESCRIPTOR.services_by_name['admin'] = _ADMIN

# @@protoc_insertion_point(module_scope)
