# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finite_consensus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='finite_consensus.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x66inite_consensus.proto\">\n\tCommReply\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.OperationStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"e\n\tSetValues\x12\t\n\x01\x66\x18\x01 \x01(\x02\x12\t\n\x01P\x18\x02 \x01(\x02\x12\x0b\n\x03SOC\x18\x03 \x01(\x02\x12\t\n\x01V\x18\x04 \x01(\x02\x12\t\n\x01Q\x18\x05 \x01(\x02\x12\x10\n\x08\x61gent_id\x18\x06 \x01(\r\x12\r\n\x05state\x18\x07 \x01(\r\"7\n\tInformAdd\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\" \n\x0cInformRemove\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\r\"q\n\x08SetParas\x12\n\n\x02k1\x18\x01 \x01(\x02\x12\n\n\x02k2\x18\x02 \x01(\x02\x12\n\n\x02k3\x18\x03 \x01(\x02\x12\r\n\x05\x61lpha\x18\x04 \x01(\x02\x12\x0c\n\x04\x62\x65ta\x18\x05 \x01(\x02\x12\x0c\n\x04gama\x18\x06 \x01(\x02\x12\n\n\x02kw\x18\x07 \x01(\x02\x12\n\n\x02kv\x18\x08 \x01(\x02**\n\x0fOperationStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\x9c\x02\n\x05\x41gent\x12.\n\x0fstart_consensus\x12\r.EmptyRequest\x1a\n.CommReply\"\x00\x12.\n\x0fremote_shutdown\x12\r.EmptyRequest\x1a\n.CommReply\"\x00\x12&\n\nset_values\x12\n.SetValues\x1a\n.CommReply\"\x00\x12)\n\x0eset_parameters\x12\t.SetParas\x1a\n.CommReply\"\x00\x12,\n\x10inform_new_agent\x12\n.InformAdd\x1a\n.CommReply\"\x00\x12\x32\n\x13inform_remove_agent\x12\r.InformRemove\x1a\n.CommReply\"\x00\x62\x06proto3')
)

_OPERATIONSTATUS = _descriptor.EnumDescriptor(
  name='OperationStatus',
  full_name='OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=415,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONSTATUS)

OperationStatus = enum_type_wrapper.EnumTypeWrapper(_OPERATIONSTATUS)
SUCCESS = 0
FAILED = 1



_COMMREPLY = _descriptor.Descriptor(
  name='CommReply',
  full_name='CommReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='CommReply.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='CommReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=88,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=104,
)


_SETVALUES = _descriptor.Descriptor(
  name='SetValues',
  full_name='SetValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f', full_name='SetValues.f', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='P', full_name='SetValues.P', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SOC', full_name='SetValues.SOC', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='V', full_name='SetValues.V', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Q', full_name='SetValues.Q', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='SetValues.agent_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='SetValues.state', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=207,
)


_INFORMADD = _descriptor.Descriptor(
  name='InformAdd',
  full_name='InformAdd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='InformAdd.agent_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='InformAdd.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='InformAdd.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=264,
)


_INFORMREMOVE = _descriptor.Descriptor(
  name='InformRemove',
  full_name='InformRemove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='InformRemove.agent_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=298,
)


_SETPARAS = _descriptor.Descriptor(
  name='SetParas',
  full_name='SetParas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k1', full_name='SetParas.k1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k2', full_name='SetParas.k2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k3', full_name='SetParas.k3', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='SetParas.alpha', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta', full_name='SetParas.beta', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gama', full_name='SetParas.gama', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kw', full_name='SetParas.kw', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kv', full_name='SetParas.kv', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=413,
)

_COMMREPLY.fields_by_name['status'].enum_type = _OPERATIONSTATUS
DESCRIPTOR.message_types_by_name['CommReply'] = _COMMREPLY
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['SetValues'] = _SETVALUES
DESCRIPTOR.message_types_by_name['InformAdd'] = _INFORMADD
DESCRIPTOR.message_types_by_name['InformRemove'] = _INFORMREMOVE
DESCRIPTOR.message_types_by_name['SetParas'] = _SETPARAS
DESCRIPTOR.enum_types_by_name['OperationStatus'] = _OPERATIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommReply = _reflection.GeneratedProtocolMessageType('CommReply', (_message.Message,), dict(
  DESCRIPTOR = _COMMREPLY,
  __module__ = 'finite_consensus_pb2'
  # @@protoc_insertion_point(class_scope:CommReply)
  ))
_sym_db.RegisterMessage(CommReply)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'finite_consensus_pb2'
  # @@protoc_insertion_point(class_scope:EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

SetValues = _reflection.GeneratedProtocolMessageType('SetValues', (_message.Message,), dict(
  DESCRIPTOR = _SETVALUES,
  __module__ = 'finite_consensus_pb2'
  # @@protoc_insertion_point(class_scope:SetValues)
  ))
_sym_db.RegisterMessage(SetValues)

InformAdd = _reflection.GeneratedProtocolMessageType('InformAdd', (_message.Message,), dict(
  DESCRIPTOR = _INFORMADD,
  __module__ = 'finite_consensus_pb2'
  # @@protoc_insertion_point(class_scope:InformAdd)
  ))
_sym_db.RegisterMessage(InformAdd)

InformRemove = _reflection.GeneratedProtocolMessageType('InformRemove', (_message.Message,), dict(
  DESCRIPTOR = _INFORMREMOVE,
  __module__ = 'finite_consensus_pb2'
  # @@protoc_insertion_point(class_scope:InformRemove)
  ))
_sym_db.RegisterMessage(InformRemove)

SetParas = _reflection.GeneratedProtocolMessageType('SetParas', (_message.Message,), dict(
  DESCRIPTOR = _SETPARAS,
  __module__ = 'finite_consensus_pb2'
  # @@protoc_insertion_point(class_scope:SetParas)
  ))
_sym_db.RegisterMessage(SetParas)



_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='Agent',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=460,
  serialized_end=744,
  methods=[
  _descriptor.MethodDescriptor(
    name='start_consensus',
    full_name='Agent.start_consensus',
    index=0,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_COMMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remote_shutdown',
    full_name='Agent.remote_shutdown',
    index=1,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_COMMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='set_values',
    full_name='Agent.set_values',
    index=2,
    containing_service=None,
    input_type=_SETVALUES,
    output_type=_COMMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='set_parameters',
    full_name='Agent.set_parameters',
    index=3,
    containing_service=None,
    input_type=_SETPARAS,
    output_type=_COMMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='inform_new_agent',
    full_name='Agent.inform_new_agent',
    index=4,
    containing_service=None,
    input_type=_INFORMADD,
    output_type=_COMMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='inform_remove_agent',
    full_name='Agent.inform_remove_agent',
    index=5,
    containing_service=None,
    input_type=_INFORMREMOVE,
    output_type=_COMMREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
