# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import finite_consensus_pb2 as finite__consensus__pb2


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.start_consensus = channel.unary_unary(
        '/Agent/start_consensus',
        request_serializer=finite__consensus__pb2.EmptyRequest.SerializeToString,
        response_deserializer=finite__consensus__pb2.CommReply.FromString,
        )
    self.remote_shutdown = channel.unary_unary(
        '/Agent/remote_shutdown',
        request_serializer=finite__consensus__pb2.EmptyRequest.SerializeToString,
        response_deserializer=finite__consensus__pb2.CommReply.FromString,
        )
    self.set_values = channel.unary_unary(
        '/Agent/set_values',
        request_serializer=finite__consensus__pb2.SetValues.SerializeToString,
        response_deserializer=finite__consensus__pb2.CommReply.FromString,
        )
    self.set_parameters = channel.unary_unary(
        '/Agent/set_parameters',
        request_serializer=finite__consensus__pb2.SetParas.SerializeToString,
        response_deserializer=finite__consensus__pb2.CommReply.FromString,
        )
    self.inform_new_agent = channel.unary_unary(
        '/Agent/inform_new_agent',
        request_serializer=finite__consensus__pb2.InformAdd.SerializeToString,
        response_deserializer=finite__consensus__pb2.CommReply.FromString,
        )
    self.inform_remove_agent = channel.unary_unary(
        '/Agent/inform_remove_agent',
        request_serializer=finite__consensus__pb2.InformRemove.SerializeToString,
        response_deserializer=finite__consensus__pb2.CommReply.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def start_consensus(self, request, context):
    """start the admm algorithm on the agent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def remote_shutdown(self, request, context):
    """start the admm algorithm on the agent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def set_values(self, request, context):
    """sets value in the finite consensus algorithm
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def set_parameters(self, request, context):
    """sets parameters
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def inform_new_agent(self, request, context):
    """inform new agent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def inform_remove_agent(self, request, context):
    """inform remove agent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'start_consensus': grpc.unary_unary_rpc_method_handler(
          servicer.start_consensus,
          request_deserializer=finite__consensus__pb2.EmptyRequest.FromString,
          response_serializer=finite__consensus__pb2.CommReply.SerializeToString,
      ),
      'remote_shutdown': grpc.unary_unary_rpc_method_handler(
          servicer.remote_shutdown,
          request_deserializer=finite__consensus__pb2.EmptyRequest.FromString,
          response_serializer=finite__consensus__pb2.CommReply.SerializeToString,
      ),
      'set_values': grpc.unary_unary_rpc_method_handler(
          servicer.set_values,
          request_deserializer=finite__consensus__pb2.SetValues.FromString,
          response_serializer=finite__consensus__pb2.CommReply.SerializeToString,
      ),
      'set_parameters': grpc.unary_unary_rpc_method_handler(
          servicer.set_parameters,
          request_deserializer=finite__consensus__pb2.SetParas.FromString,
          response_serializer=finite__consensus__pb2.CommReply.SerializeToString,
      ),
      'inform_new_agent': grpc.unary_unary_rpc_method_handler(
          servicer.inform_new_agent,
          request_deserializer=finite__consensus__pb2.InformAdd.FromString,
          response_serializer=finite__consensus__pb2.CommReply.SerializeToString,
      ),
      'inform_remove_agent': grpc.unary_unary_rpc_method_handler(
          servicer.inform_remove_agent,
          request_deserializer=finite__consensus__pb2.InformRemove.FromString,
          response_serializer=finite__consensus__pb2.CommReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
